### ISSUE TITLE
Is there an idea to translate it to other languages?

### ISSUE THREAD

**Issue by gravityNotWorking** [sumn2u/learn-javascript#1]
Hi, 
if there is, I would like to translate it into Turkish.

**Comment by sumn2u** [comment]
> Hi, if there is, I would like to translate it into Turkish.

Love to have this in Turkish. I have created [translation](https://github.com/sumn2u/learn-javascript/tree/translation) branch  where you can add the translation.  Looking forward to it.

**Comment by sumn2u** [comment]
The preview link of translation is [here](https://learn-javascript-o2wc2zrdq-iamsuman.vercel.app/).
