### ISSUE TITLE
Add JavaScript ES6 Concepts Documentation

### ISSUE THREAD

**Issue by vaibhavpnimkar** [sumn2u/learn-javascript#101]
**Issue Title:**
Add JavaScript ES6 Concepts Documentation

**Is your feature request related to a problem? Please describe.**
The current issue is a lack of comprehensive documentation on JavaScript ES6 concepts within the repository. Contributors and newcomers to the project may struggle to understand and leverage modern JavaScript features due to this gap.

**Describe the solution you'd like**
I would like to see the repository updated with thorough documentation on ES6 concepts, which should include explanations, code examples, and best practices for ES6 features like arrow functions, classes, destructuring, template literals, let and const, and more.

**Describe alternatives you've considered**
I haven't considered any alternatives as adding ES6 documentation directly to the repository seems to be the most straightforward and inclusive solution.

**Additional context**
- The existing documentation in the repository.
- The significance of up-to-date JavaScript knowledge in web development.
- My commitment to maintaining the documentation and ensuring it stays current with future ES6 updates and new JavaScript features.

**Comment by vaibhavpnimkar** [comment]
@sumn2u can you assign me this?

**Comment by AnshuWorld** [comment]
i want to contribute here please assign me

**Comment by vaibhavpnimkar** [comment]
@AnshuWorld  i have opened this issue and it is assigned to me right now

**Comment by vaibhavpnimkar** [comment]
@sumn2u which chapter no. should i add for es6 concepts??

**Comment by vaibhavpnimkar** [comment]
i have made a pr plz review

**Comment by sumn2u** [comment]
> @sumn2u which chapter no. should i add for es6 concepts??

I reviewed your PR and looks great. For chapter number, we can keep as per your PR.

**Comment by vaibhavpnimkar** [comment]
Thank you so much !!
