### ISSUE TITLE
Table of Content

### ISSUE THREAD

**Issue by Durgesh4993** [sumn2u/learn-javascript#103]
Can i create the table of content (index) which helps to user read the documentation

Example:

![image](https://github.com/swirlai/swirl-search/assets/98798977/97db55b3-a78c-40f3-a6c3-97aadbf69f2e)

**Comment by sumn2u** [comment]
Hi @Durgesh4993 , Thank you for your interest in adding a Table of Contents (ToC). We already have a [`SUMMARY.md`](https://github.com/sumn2u/learn-javascript/blob/main/en/SUMMARY.md) file that includes the ToC.
