### ISSUE TITLE
Changing Twitter logo in the Website

### ISSUE THREAD

**Issue by SusheelThapa** [sumn2u/learn-javascript#107]
As seen in the image below, website has same old twitter logo, I want to change it to new one.

Please assign me.

![image](https://github.com/sumn2u/learn-javascript/assets/83917129/c88f405c-b084-4056-80db-03ce2778b50d)

**Comment by SusheelThapa** [comment]
@sumn2u  I couldn't figure the how css is being attach to the website. Can you help me out?

**Comment by mohitparmar1** [comment]
i would like to work on this issue please assign to me!

**Comment by SusheelThapa** [comment]
![image](https://github.com/sumn2u/learn-javascript/assets/83917129/7b33d816-952e-4055-a74e-385cd0ec22aa)
@sumn2u  It seems that we are using lower version of fontawesome. Is there any way to upgrade it?

**Comment by Arnalv** [comment]
It seems that the issue has been fixed, looking at the website. 
![image](https://github.com/sumn2u/learn-javascript/assets/140675437/ae811be1-aaa7-443b-8d6a-b11e6df466d2)

**Comment by sumn2u** [comment]
Yes @Arnalv. Thanks for having a look into it. 🙏
