### ISSUE TITLE
Adding `for ... in` loop in Looping section

### ISSUE THREAD

**Issue by SusheelThapa** [sumn2u/learn-javascript#108]
@sumn2u  Please assign me.

**Comment by sumn2u** [comment]
> @sumn2u Please assign me.

Hi @SusheelThapa , we already have some introduction about `for ... in` loop [here](https://javascript.sumankunwar.com.np/en/loops/for.html). Are you planning to add more content here?

**Comment by SusheelThapa** [comment]
Yeah I can write in about for in below format.

## For
## For in

Or shall I create different page of `for ... in`.

**Comment by sumn2u** [comment]
I think it's better to put it in same place as the introductory part is done there .

**Comment by SusheelThapa** [comment]
Okay i will keep `for` loop and `for .. in` in same files. Will that be ok?

**Comment by SusheelThapa** [comment]
This issue has been address in #113 PR
