### ISSUE TITLE
Space and Time complexity

### ISSUE THREAD

**Issue by sumn2u** [sumn2u/learn-javascript#112]
Considering space and time complexity is a significant aspect of programming that ensures code efficiency, scalability, and maintainability. Having a brief introduction to these concepts, followed by example, can greatly benefit JavaScript developers.

**Comment by starvader13** [comment]
I would love to take this issue.

**Comment by starvader13** [comment]
There are some basic details I want to know before I start working on this.

- [ ] Can I change the chapter numbers as I want to put the `complexity` chapter after the `loops`, `functions` and `objects` chapter?
- [ ] Till what details should I go into the complexity chapter?
- [ ] Can you tell whether the given structure is satisfactory or not?
```bash
en/complexity
├── README.md
├── space-complexity.md
└── time-complexity.md
```

**Comment by auth-02** [comment]
Certainly! Considering space and time complexity is crucial in programming for efficient, scalable, and maintainable code.
Would like to contribute to this issue.

**Comment by sumn2u** [comment]
> @sumn2u There are some basic details I want to know before I start working on this.
> 
> * [ ]  Can I change the chapter numbers as I want to put the `complexity` chapter after the `loops`, `functions` and `objects` chapter?

 Yes
> * [ ]  Till what details should I go into the complexity chapter?

Surface level that gives readers context would be enough.

> * [ ]  Can you tell whether the given structure is satisfactory or not?
> 
> ```shell
> en/complexity
> ├── README.md
> ├── space-complexity.md
> └── time-complexity.md
> ```

Looks good.

**Comment by starvader13** [comment]
> Surface level that gives readers context would be enough.

Will do that. Thanks for the info.

**Comment by rajumtr777** [comment]
@sumn2u can I pick this?

**Comment by dhirajs16** [comment]
Hey @sumn2u, is this issue still open. Can i participate to resolve it?

**Comment by sumn2u** [comment]
> Hey @sumn2u, is this issue still open. Can i participate to resolve it?

Yes, we already have the structure in [place](https://github.com/sumn2u/learn-javascript/tree/main/en/complexity). We just need to add the content.

**Comment by dhirajs16** [comment]
@sumn2u  Thanks for assigning me for this. Looking forward to work on this.

**Comment by dhirajs16** [comment]
Hey @sumn2u,  I've added content in the time and space complexity sections. Please have a look and tell if i need to do some adjustments or it will do the job.
