### ISSUE TITLE
Update in Object section 

### ISSUE THREAD

**Issue by SusheelThapa** [sumn2u/learn-javascript#119]
I want to update object section with following heading.

```
Factory Functions
Constructor Functions
Dynamic Nature of Objects
Constructor Property
```

**Comment by sumn2u** [comment]
Hi @SusheelThapa , let me know if you need any assistance from me.

**Comment by SusheelThapa** [comment]
@sumn2u Currently, I am having exam. I will soon update as soon as exam finished.

**Comment by Hachondeoro** [comment]
Hi @sumn2u . Can I get assigned this task?

**Comment by sumn2u** [comment]
> Hi @sumn2u . Can I get assigned this task?

Sure.
