### ISSUE TITLE
Automate reports on english sections to be translated into other languages

### ISSUE THREAD

**Issue by moustaphaotf** [sumn2u/learn-javascript#131]
**Is your feature request related to a problem? Please describe.**
I'm new to github and workflows... through the process of trqnslations there may occur sometimes that translators need to know which sections they have to must focus on. Given some changes in one section of a chapter, it may be interesting to signal that in other language there may be fixes to be done for coherence (and what have been updated to the original version)

**Describe the solution you'd like**
Nothing in mind currently.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by moustaphaotf** [comment]
Hello !
I've been working on a solution up to this time what I've made up is to use github workflows to listen up to push & pull_request close event and then check if there have been changes made to the main folder `en/`. After that, the workflow finds out the differences and create a new issue with labels | assignees | description based on what the diffs are made of.

Here is the description of the whole process:

1. A user forks the repository.
2. They make contributions and push changes to their forked repository.
3. They submit a pull request to the repository to have their changes merged into the main branch.
4. After the pull request is merged, a check is performed to test if there are updates to the "en/" folder in the main repository.
5. If there are updates to the "en/" folder, the workflow automaticaly create a GitHub issue to notify maintainers that there is a need for translation.

I have a [bare solution that I experienced with ](https://github.com/moustaphaotf/testing-workflows/issues) where u can see workflows automaticaly generated.

Check it out and let's talk about it !
I'm also open to propositions to enhance the process

**Comment by moustaphaotf** [comment]
@sumn2u if you get some free time, we'll have to discuss about this solution or find alternatives if possible.

**Comment by sumn2u** [comment]
> @sumn2u if you get some free time, we'll have to discuss about this solution or find alternatives if possible.

Thanks @moustaphaotf  for the awesome script. Is there a way to setup in our current workflow? Would love to see it in action.

**Comment by Shashankpantiitbhilai** [comment]
Assign it to me
