### ISSUE TITLE
Screen properties table has duplicates  

### ISSUE THREAD

**Issue by gnwx** [sumn2u/learn-javascript#14]
| Property | Description |
| :--- | :--- |
| `height` | Represents the pixel height of the screen. |
| `left` | Represents the pixel distance of the current screen’s left side. |
| `pixelDepth` | A read-only property that returns the bit depth of the screen. |
| `top` | Represents the pixel distance of the current screen’s top. |
| `width` | Represents the pixel width of the screen. |
| `orientation` |  Returns the screen orientation as specified in the Screen Orientation API |
| `availTop` | A read-only property that returns the first pixel from the top that is not taken up by system elements. |
| `availWidth` | A read-only property that returns the pixel width of the screen excluding system elements. |
| `colorDepth` | A read-only property that returns the number of bits used to represent colors. |
| `height` | Represents the pixel height of the screen. |
| `left` | Represents the pixel distance of the current screen’s left side. |
| `pixelDepth` | A read-only that returns the bit depth of the screen. |
| `top` | Represents the pixel distance of the current screen’s top. |
| `width` | Represents the pixel width of the screen. |
| `orientation` |  Returns the screen orientation as specified in the Screen Orientation API |

As you can see above, the `height`, `left`, `pixelDepth`, `top`, `width`, `orientation` properties duplicated. 

You can find file here: https://github.com/sumn2u/learn-javascript/blob/main/en/browser-object-model-bom/screen.md

**Comment by sumn2u** [comment]
Great catch. Thanks for pointing it out 🙏
