### ISSUE TITLE
Adding Closures 

### ISSUE THREAD

**Issue by vaibhavpnimkar** [sumn2u/learn-javascript#142]
**Is your feature request related to a problem? Please describe.**
I've noticed that the current documentation lacks a comprehensive explanation of JavaScript closures, and this creates difficulties for learners who are trying to grasp this fundamental concept. Closures are a critical topic in JavaScript, and it's essential to have a dedicated chapter that covers them in detail.

**Describe the solution you'd like**

I would like to request the addition of a new chapter in the documentation specifically dedicated to explaining JavaScript closures. This chapter should provide a clear and concise explanation of what closures are, how they work, and their practical applications in JavaScript. It should include code examples and real-world scenarios to illustrate the concept effectively.

**Describe alternatives you've considered**
One alternative would be to continue using external resources to supplement the lack of information in the current documentation. However, having a dedicated chapter within the official documentation would be more beneficial, as it ensures consistency and reliability in the learning material.

**Comment by sumn2u** [comment]
Fixed in #147
