### ISSUE TITLE
Adding documents on `setTimeout()` and `setInteval()` 

### ISSUE THREAD

**Issue by Lensco825** [sumn2u/learn-javascript#150]
I'd like to add documents on the `setTimeout()` and `setInterval()` functions since I didn't see them in the book.

 I'll put both of them under the [function](https://javascript.sumankunwar.com.np/en/functions/) section of the book since it's mainly used to change the function's start time and repetition time. Please give me your thoughts on this, especially on where I place these documents.

Please assign this issue to me and add a "hacktoberfest" label to it, currently I'm participating in the 2023 Hacktoberfest.

**Comment by serv-er** [comment]
hello @sumn2u  can you assign it to me if no one working on this

**Comment by Lensco825** [comment]
@serv-er  I've already completed the documents and I made a pull request for it today that was merged. I'm sorry for taking this assignment from you, but you could also help make new documents (maybe a whole new section on Javascript for web development?) or add more examples to mine.
