### ISSUE TITLE
updating the twitter logo

### ISSUE THREAD

**Issue by barkhaaroraa** [sumn2u/learn-javascript#158]
**Describe the bug**
replacing the old logo with X (the new logo)

**To Reproduce**
1. Go to the website and look on the top right corner

**Expected behavior**
should have the new logo

**Screenshots**
<img width="145" alt="image" src="https://github.com/sumn2u/learn-javascript/assets/115429121/956543fd-2018-4a06-9977-18660b3c3700">

**Comment by HarshitVashisht11** [comment]
Can you assign this issue to me

**Comment by barkhaaroraa** [comment]
Could you assign this issue to me @sumn2u

**Comment by JatinPhogat** [comment]
Hii, @sumn2u i am interested in working on this issue . I see that it is currently assigned to soms other person but 3 days has passed and still it is pending state , can i work on it??

**Comment by ktriggsdev** [comment]
Hey @sumn2u if no-one has been working on this issue yet, can you assign it to me?

**Comment by sumn2u** [comment]
> Hey @sumn2u if no-one has been working on this issue yet, can you assign it to me?

Sure.

**Comment by ktriggsdev** [comment]
> > Hey @sumn2u if no-one has been working on this issue yet, can you assign it to me?
> 
> Sure.
> 

Thanks, I will start work on this issue tomorrow. Just to check, does the fontawesome package need updating to the latest version still?

**Comment by sumn2u** [comment]
> > > Hey @sumn2u if no-one has been working on this issue yet, can you assign it to me?
> > 
> > 
> > Sure.
> 
> Thanks, I will start work on this issue tomorrow. Just to check, does the fontawesome package need updating to the latest version still?

I believe so.

**Comment by ktriggsdev** [comment]
@sumn2u Hey, I am having trouble locating the styles css file and the main index.html file, could you please point me in the right direction? when I clone the repository these files don't show up for some reason

**Comment by ktriggsdev** [comment]
@sumn2u it seems you need to do the following, as gitbook does not include all the main files in the repository, you will need to update the main index.html page at gitbook to include the following inside the head element:

```html
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
```
**important!:** make sure to remove the old font stylesheet from the head element before adding the new one

also in the html file change the following:

```html
<i class="fa fa-twitter"></i>
```

to:

```html 
<i class="fa-brands fa-x-twitter"></i>
```

this should fix the issue

**Comment by sumn2u** [comment]
> @sumn2u it seems you need to do the following, as gitbook does not include all the main files in the repository, you will need to update the main index.html page at gitbook to include the following inside the head element:
> 
> ```
> <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
> ```
> 
> **important!:** make sure to remove the old font stylesheet from the head element before adding the new one
> 
> also in the html file change the following:
> 
> ```
> <i class="fa fa-twitter"></i>
> ```
> 
> to:
> 
> ```
> <i class="fa-brands fa-x-twitter"></i>
> ```
> 
> this should fix the issue

Thank you for the suggestion. Unfortunately, the solution you provided did not work for me. As a workaround, I used a different solution.
```css
.fa.fa-twitter{
	font-family:sans-serif;
}
.fa.fa-twitter::before{
	content:"𝕏";
	font-size:1.2em;
}
```
