### ISSUE TITLE
I want to add JavaScript animation resources

### ISSUE THREAD

**Issue by BALASARVAN12** [sumn2u/learn-javascript#181]
**Is your feature request related to a problem? Please describe.**
Users often encounter challenges finding comprehensive and up-to-date resources for JavaScript animations. These resources could include libraries, tutorials, frameworks, or best practices. The lack of centralized, curated, and comprehensive information can frustrate individuals looking to create engaging JavaScript animations.
**Describe the solution you'd like**
I would like to propose adding a curated list or a dedicated section within our repository that focuses specifically on JavaScript animation resources. This section could include links to libraries, tutorials, articles, and frameworks that assist developers in creating animations using JavaScript. Could further aid users in finding the most relevant resources for their needs.
**Describe alternatives you've considered**
One alternative might be creating a separate website solely dedicated to JavaScript animation resources. However, integrating this within our existing repository would centralize the information for users already engaging with our project, providing added value without needing separate navigation.
**Additional context**
Adding this feature could significantly enhance the usability and value of our repository, catering to the needs of developers seeking guidance or resources on implementing JavaScript animations. This enhancement aligns intending to provide comprehensive resources and support within our community.

**Comment by naeem4633** [comment]
Is this still available? 
I want to take it up. I can add libraries, tutorials and frameworks, and other supporting resources for JS animations.

**Comment by sumn2u** [comment]
> Is this still available? I want to take it up. I can add libraries, tutorials and frameworks, and other supporting resources for JS animations.

Yes, it is.  I've assigned it to you.

**Comment by naeem4633** [comment]
noted.
