### ISSUE TITLE
Want To add Arrow Function Content

### ISSUE THREAD

**Issue by VaibhavSharma24** [sumn2u/learn-javascript#184]
**Describe the solution you'd like**
Want to add the content about the ES6 JS arrow function it's commonly being used nowadays everwhere and it's crucial to add and will increase the quality of the content.

**Comment by sumn2u** [comment]
> **Describe the solution you'd like** Want to add the content about the ES6 JS arrow function it's commonly being used nowadays everwhere and it's crucial to add and will increase the quality of the content.

We already have definition of it [here](https://javascript.sumankunwar.com.np/en/miscellaneous/ECMA-script.html). Is it possible to add examples of ES6 syntaxes?

**Comment by VaibhavSharma24** [comment]
@sumn2u Yeah nice idea i think adding some simple few examples of it will make it more easy to understand.

**Comment by VaibhavSharma24** [comment]
@sumn2u I have made the PR for this issue Please review it as today is the last day for hactoberfest

Please feel free to mention if any changes needed.

 Loved your book tho 😊

**Comment by sumn2u** [comment]
> @sumn2u I have made the PR for this issue Please review it as today is the last day for hactoberfest
> 
> Please feel free to mention if any changes needed.
> 
> Loved your book tho 😊

The PR looks great and thanks for the compliment.
