### ISSUE TITLE
Typo in exercises section

### ISSUE THREAD

**Issue by gnwx** [sumn2u/learn-javascript#19]
Small typo missing "t":
"The Get the Tiles! problem"
https://github.com/sumn2u/learn-javascript/blob/main/en/exercises/get-the-titles.md

**Comment by sumn2u** [comment]
Thanks for pointing the issue.  The issue is fixed in [this](https://github.com/sumn2u/learn-javascript/commit/fa2c2bc5d7e109e2f56f4a4ae84e025cda783867) commit.
