### ISSUE TITLE
How Javascript Works Behind the Scene

### ISSUE THREAD

**Issue by thejuggernaut01** [sumn2u/learn-javascript#204]
It would be helpful to include a separate chapter that covers How Javascript works behind the scene. 

adding a chapter on the inner workings of JavaScript equips developers with a deeper understanding of the language but also enhances their ability to write efficient, performant, and reliable code, making them more proficient and versatile in their roles.

**Comment by thejuggernaut01** [comment]
> It would be helpful to include a separate chapter that covers How Javascript works behind the scene.
> 
> adding a chapter on the inner workings of JavaScript equips developers with a deeper understanding of the language but also enhances their ability to write efficient, performant, and reliable code, making them more proficient and versatile in their roles.

Kindly assign this to me. Thank you.

**Comment by thejuggernaut01** [comment]
@sumn2u you are welcome.

**Comment by poojaindulkar** [comment]
@sumn2u, Thank you so much for assigning the issue to me! I'm excited to contribute. Could you please provide some guidance on how to proceed with this? Are there any specific steps, guidelines, or preferences you have in mind for the content of the chapter? I want to make sure I align with your expectations.

Additionally, if there's a particular approach or outline you have in mind, I'd love to discuss it further. I'm open to collaboration and would appreciate any feedback you may have throughout the process.

Looking forward to your guidance.

**Comment by sumn2u** [comment]
> Could you please provide some guidance on how to proceed with this? Are there any specific steps, guidelines, or preferences you have in mind for the content of the chapter? I want to make sure I align with your expectations.
> 

Certainly, we can include a dedicated chapter that delves into the inner workings of JavaScript. This can cover important topics such as its engine, execution context, call stack, memory heap, runtime environment, and event loop. We have already covered other related topics such as its single-threaded, asynchronous nature, Promises, async/await, and debugging tools which we can reference.

> Additionally, if there's a particular approach or outline you have in mind, I'd love to discuss it further. I'm open to collaboration and would appreciate any feedback you may have throughout the process.

The project's [README.md](https://github.com/sumn2u/learn-javascript?tab=readme-ov-file#typographic-conventions) defines the typographic conventions, project structure, and contributing guidelines used, you can follow it.

**Comment by Hachondeoro** [comment]
Hi @sumn2u . I added this chapter and submitted a pull request, please check :)
