### ISSUE TITLE
Introduction of Closures, Recursive Functions, Set Interval and  Set Timeout topics in  Functions chapter.

### ISSUE THREAD

**Issue by sumn2u** [sumn2u/learn-javascript#209]
Here are some topics missing from the functions chapter that would be helpful to have: closures, recursive functions, set interval, and set timeout.

**Comment by klever34** [comment]
@sumn2u I'd like to contribute by writing about some of the topics listed above. How do I go about that?

**Comment by sumn2u** [comment]
> @sumn2u I'd like to contribute by writing about some of the topics listed above. How do I go about that?

Thank you for your interest in writing those chapters, but they have already been covered. Would you like to contribute [this](https://github.com/sumn2u/learn-javascript/issues/181) one instead?
