### ISSUE TITLE
Enhancement of interview questions (ES6 classes)

### ISSUE THREAD

**Issue by deyantomov** [sumn2u/learn-javascript#216]
I want to update the intermediate level interview questions with a section about ES6 classes with the following questions:

```
1. What are JavaScript classes?
2. Class members (fields and methods) and class properties (getters and setters)
4. Explain constructor functions
5. Static members vs Instance members
6. Member visibility
```

**Comment by sumn2u** [comment]
> I want to update the intermediate level interview questions with a section about ES6 classes with the following questions:
> 
> ```
> 1. What are JavaScript classes?
> 2. Class members (fields and methods) and class properties (getters and setters)
> 4. Explain constructor functions
> 5. Static members vs Instance members
> 6. Member visibility
> ```

@deyantomov These topics are helpful. We would love to see your contributions.
