### ISSUE TITLE
The Server is not deploying Locally.

### ISSUE THREAD

**Issue by THEBOSS0369** [sumn2u/learn-javascript#227]
**Describe the bug**
The Server is not deploying Locally when running it using npm start 

**To Reproduce**
1. I used Gitbook serve for then a type error came i uploaded that error on gpt and it told me that my node js version is different then the gitbook's version (the screen shot is in the screenshot section down below) Chat gpt told me This    
   **"GitBook 3.x may not be compatible with newer Node.js versions, consider using an older version of Node.js."**
2. Then i run the **npm run start** command to check whether the website is running or not on my system then it was checking some requirements and then  after this line 
        `info: found 3 asset files
        warn: "this.generator" property is deprecated, use "this.output.name" instead
        warn: "navigation" property is deprecated
        warn: "book" property is deprecated, use "this" directly instead
        warn: "options" property is deprecated, use config.get(key) instead`
it suddenly stops.

**Expected behavior**
The server should have been started without any error.

**Screenshots**
Screenshot for gitbook serve 
![error](https://github.com/user-attachments/assets/5cc37693-0be7-4c9c-b6e6-f81b65cf8d55)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Microsoft Edge
 - Version 127.0.2651.98

**Additional context**
Also if possible, please add the procedure to run this website in local , like what type of libraries we have to install, etc.

**Comment by sumn2u** [comment]
Hi @THEBOSS0369, I tried with Node `22.6.0` and it's working. I believe you have done `npm install` before running `npm start` right?

**Comment by THEBOSS0369** [comment]
@sumn2u Yes i have run npm install, if the website is running in yours then maybe the error will be from my system. I will try removing the whole repository from my system and installing it again maybe the issue may get resolved.

**Comment by THEBOSS0369** [comment]
Now It's working maybe this issue was from my side. My apology for this Unnecessary Issue.
