### ISSUE TITLE
Non-Responsive Content in Interview Section

### ISSUE THREAD

**Issue by sumn2u** [sumn2u/learn-javascript#237]
In the interview section, the content is currently not responsive on mobile devices, resulting in a suboptimal user experience. Please update the styles to ensure that the content adapts seamlessly to various screen sizes, improving accessibility and usability for mobile users.

![image](https://github.com/user-attachments/assets/6f1adc91-d5f9-411e-97fd-8f0811122b7e)

**Comment by Abhishek-IITP** [comment]
Please assign me

**Comment by Abhishek-IITP** [comment]
Due to some personal issues, I won't be able to be available so please unassign me kindly.....

**Comment by clairebeware** [comment]
Hi, can you please assign me to this issue?

**Comment by sumn2u** [comment]
> Hi, can you please assign me to this issue?

Sure.

**Comment by clairebeware** [comment]
Hello @sumn2u I've figured out how to fix the issue on the interview pages, I can make the edit to the style.css page for just the interview sections or for all of the sections if you prefer, it looks like some of the other sections overflow as well just not as much: 
<img width="567" alt="Screenshot 2024-10-12 at 11 28 36 AM" src="https://github.com/user-attachments/assets/fa1e1d29-d711-4fda-b773-4cd0ab0715f8">

**Comment by sumn2u** [comment]
Wow, looks awesome. Would be great if we apply it for all sections.

**Comment by clairebeware** [comment]
Okay will do!
