### ISSUE TITLE
Navigation of scope to respective section

### ISSUE THREAD

**Issue by sumn2u** [sumn2u/learn-javascript#239]
Each scope should have a hyperlink, so that when clicked, it directs the user to the relevant content section.

![Screenshot 2024-10-08 at 9 27 16 AM](https://github.com/user-attachments/assets/557c4c3a-00c5-4757-bd22-514cedf88a10)

**Comment by hemangtk** [comment]
Hey @sumn2u I'm interested in working on this issue can I know where this is locatated exactly so I can start working on it right away

**Comment by sumn2u** [comment]
> Hey @sumn2u I'm interested in working on this issue can I know where this is locatated exactly so I can start working on it right away

Sure. You can find it [here](https://github.com/sumn2u/learn-javascript/blob/main/en/interview-questions/basic-level.md?plain=1#L206-L208).

**Comment by hemangtk** [comment]
got it!! @sumn2u  can you assign me the issue so i can start working right away

**Comment by hemangtk** [comment]
Hey just needed some help while previewing the code 
could you help me with that?

**Comment by sumn2u** [comment]
> Hey @sumn2u just needed some help while previewing the code could you help me with that?

Certainly! You can run the application on your local machine and make changes to the specified file. Once you've added the logic, test it to ensure everything works as expected. After confirming it's functioning correctly, you can submit your changes.

**Comment by hemangtk** [comment]
i have applied the logic but im not able to open the preview in the webpage 
could you help me with that @sumn2u ?
thank you!!

**Comment by sumn2u** [comment]
If you're having trouble running the application on your system, you can create a pull request with your changes. The code will be automatically deployed, and a preview link will be generated for you to review.

**Comment by hemangtk** [comment]
> If you're having trouble running the application on your system, you can create a pull request with your changes. The code will be automatically deployed, and a preview link will be generated for you to review.

Cool!! 
thank you so much!!

**Comment by hemangtk** [comment]
hey!! @sumn2u  just made a pr do check it out and let me know if there are some changes to be made im sorry..as i was not able to preview the code written!! 
thank you!!
