### ISSUE TITLE
We can add a js code editor.

### ISSUE THREAD

**Issue by raj-adi00** [sumn2u/learn-javascript#262]
Enhancement
Apart from Reading we should provide option for practice. 

We will implement a js code editor and it is easy to implement on browser to practice js coding.

Alternative way is to direct some other website.

**Comment by sumn2u** [comment]
Hi @raj-adi00, thanks for the feature request. We have already a browser editor may be we can reuse it? 

https://javascript.sumankunwar.com.np/en/exercises/console.html
