### ISSUE TITLE
Web APIs and AJAX Chapter

### ISSUE THREAD

**Issue by sumn2u** [sumn2u/learn-javascript#30]
Would be nice to have a separate chapter that talks about Web APIs and AJAX as they are fundamental for creating interactive and dynamic web applications

**Comment by StrixV54** [comment]
I want to work on this  but where are these chapters? Or Do I need to add them?

**Comment by sumn2u** [comment]
> I want to work on this but where are these chapters? Or Do I need to add them? Also this project looks cool, I will be happy to add to this.

Hi @StrixV54, these are the new chapters that need to be added. We would be more than happy if you could do this. Let me know if you need any help.

**Comment by bEluga0000** [comment]
can you assign me this issue so that i can work on this

**Comment by bEluga0000** [comment]
@sumn2u How to add chapter number and page number .

**Comment by sumn2u** [comment]
@bEluga0000 To add a chapter you can add following section in  top of your `.md` file.
```
---
layout: editorial
chapter: <chapter_id>
pageNumber: <page_number>
description: <small_description_of_content>
---
```
Additionally, to preview the newly created chapter in the sidebar, it needs to be added to the SUMMARY.md file as shown [here](https://github.com/sumn2u/learn-javascript/blob/main/en/SUMMARY.md?plain=1#L83).
