### ISSUE TITLE
Design Patterns in JavaScript

### ISSUE THREAD

**Issue by sumn2u** [sumn2u/learn-javascript#31]
It would be nice to have a chapter that describes design patterns in JavaScript. Design patterns are proven solutions to common software design problems that help in writing maintainable, scalable, and efficient code.

**Comment by CrownPab** [comment]
Hello, may I be assigned this chapter?

**Comment by sumn2u** [comment]
> Hello, may I be assigned this chapter?

Sure.

**Comment by Haribhajank** [comment]
Hey @sumn2u can you assign this to me, I am interested to work on this .

**Comment by CrownPab** [comment]
I already have all three categories of the design patterns done. Today I will be proofreading and then submitting a PR

**Comment by Haribhajank** [comment]
Ok @CrownPab , I got it .
