### ISSUE TITLE
Server-side JavaScript

### ISSUE THREAD

**Issue by sumn2u** [sumn2u/learn-javascript#33]
A chapter on server-side JavaScript would give learners a full understanding of its applications in both front-end and back-end development, preparing them for diverse web development challenges. So, it would be nice to have it here.

**Comment by ChiragAgg5k** [comment]
Hey, I was curious about what this chapter intends to cover. Is it about how JavaScript can run on the server side using NodeJS, or does it cover topics of server-side rendering using frameworks like Nextjs? Or is it both?

**Comment by sumn2u** [comment]
> Hey, I was curious about what this chapter intends to cover. Is it about how JavaScript can run on the server side using NodeJS, or does it cover topics of server-side rendering using frameworks like Nextjs? Or is it both?

Hi @ChiragAgg5k , its about both and has not been covered yet. If you are interested then i can assign you.

**Comment by ChiragAgg5k** [comment]
Yeah i am interested!

**Comment by ChiragAgg5k** [comment]
@sumn2u hey there. i am a bit confused on how to add a new document. By following the `README.md` in the src directory, i made a new folder named `server-side` inside which i made a `README.md` file with some boilerplate text. But on running the dev server using `yarn start` , its neither showing on the navbar, nor available by directly going to the url:

```
ENOENT: no such file or directory, stat '/Users/chiragagg5k/Desktop/coding_stuff/repos/learn-javascript/_book/en/server-side/index.html'
```
<img width="1230" alt="Screenshot 2023-09-28 at 4 55 54 PM" src="https://github.com/sumn2u/learn-javascript/assets/110609663/65bffd07-aac4-4d48-a998-f56bb24a596d">

**Comment by sumn2u** [comment]
Hello @ChiragAgg5k, thanks for taking care of the server-side chapter. To view any new changes made to a newly created file, it's necessary to restart the server after its creation. I recommend that you restart the server.  Additionally, to preview the newly created chapter in the sidebar, it needs to be added to the `SUMMARY.md` file as shown [here](https://github.com/sumn2u/learn-javascript/blob/main/en/SUMMARY.md?plain=1#L83).

If restarting the server didn't help then you can run `yarn build` followed by `yarn start`. Let me know if you still have a problem.

**Comment by ChiragAgg5k** [comment]
Thanks, I was able to get that working. I was also curious what chapter number would you like this one to be?

**Comment by sumn2u** [comment]
> Thanks, I was able to get that working. I was also curious what chapter number would you like this one to be?

Let's put it under chapter 20 and update the exercises chapter to 21.
