### ISSUE TITLE
Refine ReadMe.md file. Edit language and formatting (English). 

### ISSUE THREAD

**Issue by bj-rutledge** [sumn2u/learn-javascript#38]
Though I have not yet seen any blatant errors in the readme file, I would like to propose some minor changes to the formatting and language. For example, in the Introduction section, the book title is referenced. The title should be in italics (note: this is not a personal gripe but proper English formatting). Next, I would like to go through the file and evaluate the grammar and language used. 

I'd be happy to take this on under the Hactoberfest tag!

**Comment by sumn2u** [comment]
Thanks for the initiative. 🙏

**Comment by bj-rutledge** [comment]
Great! I have forked the repo. I will review the material more thoroughly and create branches for edits I feel will enhance the reader's experience. I'll likely have a PR on or after October 1st. Thanks for opening this up! It will be fun! 

Please let me know if you have any conventions you will want to hold to throughout the book (coding conventions, names for things, etc.). 

Finally, please know that I will never be offended if my PR is not accepted, especially on something like this, where it's a bit more subjective rather than objective. 😉

**Comment by bj-rutledge** [comment]
I submitted a PR for a small edit. This is my first time contributing to someone else's project, so I wanted my first PR to be a small change to get the flow with low stakes.
