### ISSUE TITLE
JavaScript Interview Questions [ Intermediate Level ]

### ISSUE THREAD

**Issue by sumn2u** [sumn2u/learn-javascript#40]
A curated list of JavaScript questions that helps learners to improve their understanding of the language and develop the skills they need to be successful JavaScript developers.

**Comment by deveshidwivedi** [comment]
hello, please assign me this issue under hacktoberfest 2023. i have understanding of javascript language.

**Comment by deveshidwivedi** [comment]
sir could you please tell me whether the interview questions are going to constitute a different chapter or whether they'll be in the existing chapters?

**Comment by sumn2u** [comment]
> sir could you please tell me whether the interview questions are going to constitute a different chapter or whether they'll be in the existing chapters?

There will be a dedicated chapter with various levels of questions. The chapter page will provide an overview of the content and list the different levels of questions. Clicking on each level will redirect the user to the corresponding set of questions, similar to the example shown [here](https://github.com/sumn2u/learn-javascript/tree/main/en/miscellaneous).
