### ISSUE TITLE
JavaScript Interview Questions [ Advance Level ]

### ISSUE THREAD

**Issue by sumn2u** [sumn2u/learn-javascript#41]
A curated list of JavaScript questions that helps learners to improve their understanding of the language and develop the skills they need to be successful JavaScript developers.

**Comment by TANYA03GUPTA** [comment]
hey i would like to help you out with this one. CAn you assign it to me?

**Comment by TANYA03GUPTA** [comment]
@sumn2u I am facing a problem, i have added the .md file and seen the preview it is showing everything i have added in the file on the site, but when i send pr , the vercel deployment fails, what do you suggest i do?

**Comment by sumn2u** [comment]
@TANYA03GUPTA In your PR, you committed  both `package-lock.json` and `yarn.lock` files where `package-lock.json` has some problem with commit hashes. I suggest you not to commit those files as this task doesn't require updates on it. It should fix the problem.

![Screenshot 2023-10-02 at 6 02 17 AM](https://github.com/sumn2u/learn-javascript/assets/6531541/982943f9-59f7-48f2-8de6-f55d113e3511)
