### ISSUE TITLE
Translation - [French][Part II]

### ISSUE THREAD

**Issue by sumn2u** [sumn2u/learn-javascript#57]
Translating this book can be a great way to expand its reach and connect with more readers. It's worth considering translating the chapters to make the book accessible to a wider audience. As agreed [here](https://github.com/sumn2u/learn-javascript/issues/3#issuecomment-1744304323) the part II will consider all remaining chapters including  exercises/ loops/ miscellaneous/ objects/ promise-async-await chapters.

**Comment by moustaphaotf** [comment]
Alright, thank you !
I'm working currently on miscellaneous/, already done exercises/ and loops/

**Comment by scheuerkev** [comment]
Good job @moustaphaotf ! 
I've included this tip for French readers in a note that you can read in Preface.md. As you will see, I have deliberately not translated certain concepts to make them stick as closely as possible to the way there are used in JavaScript. For example, I've left some terms such as 'closure' and 'handler' as they are. Even if they have an equivalent in French, I preferred to try and explain the concept and leave the word as it is, if you want to keep the same approach. Happy translating!

**Comment by moustaphaotf** [comment]
Got it !
Thanks ^

**Comment by sumn2u** [comment]
@moustaphaotf How's the translation coming along? Do you require any assistance?
