### ISSUE TITLE
Corrections to be added to the englis version

### ISSUE THREAD

**Issue by moustaphaotf** [sumn2u/learn-javascript#58]
While taking the chapters based on their english version to tanslate into french. I've nitices in some points, errors either grammatical or orhographic. Other orrors involve also typo on some links.

I report it here cause after having done with the translation, I will also tackle down the task.

**Comment by TANYA03GUPTA** [comment]
hey @moustaphaotf I could help you out with the english transaltions. Kindly asssign it to me.

**Comment by moustaphaotf** [comment]
Hello @TANYA03GUPTA , i was talking about errors i've encountered on the english version while translating it into french.

It include for instance the miscellaneous chapter and others that have been assigned to me to translate here #57

**Comment by moustaphaotf** [comment]
Just ended my translation jobs on the five chapters that were assigned to me
I'm ready to push the corrections I've taking about earlier
Possible ?

**Comment by sumn2u** [comment]
> Hello @sumn2u I just ended my translation jobs on the five chapters that were assigned to me I'm ready to push the corrections I've taking about earlier Possible ?

Sure.
