### ISSUE TITLE
JavaScript Interview Questions [ Updated: Basic Level ] 

### ISSUE THREAD

**Issue by sumn2u** [sumn2u/learn-javascript#69]
We already have interview questions, but they are limited. It would be nice to have more questions to help candidates better prepare themselves.

**Comment by somuyakhandelwal** [comment]
I can help you on this in adding more interview questions on js like we have given a question bank in my course which has some really good question set in all levels from basic to advanced....

**Comment by ayushi-ras** [comment]
Hey! Plz assign me this

**Comment by tvermaashutosh** [comment]
@sumn2u 
Please assign me this issue. I will work very diligently to complete this task.

**Comment by sumn2u** [comment]
> @sumn2u Please assign me this issue. I will work very diligently to complete this task.

I assigned this task to @ayushi-ras. Could you please coordinate with her? If not, there are other tasks that also require support.

**Comment by somuyakhandelwal** [comment]
> > @sumn2u Please assign me this issue. I will work very diligently to complete this task.
> 
> I assigned this task to @ayushi-ras. Could you please coordinate with her? If not, there are other tasks that also require support.

Yaa sure I am willing to co ordinate with her 
@sumn2u

**Comment by AnshuWorld** [comment]
i want to contribute here please assign me

**Comment by kishanrajput23** [comment]
@sumn2u can you assign this issue to me. I'll add more interview questions.
