### ISSUE TITLE
add license to readme file

### ISSUE THREAD

**Issue by barkhaaroraa** [sumn2u/learn-javascript#95]
**Describe the bug**
the license hasnt been mentioned on the readme file

**To Reproduce**
1. Go to 'readme.md'
scroll all the way down

**Comment by sumn2u** [comment]
Nice catch. I added the license in [this](https://github.com/sumn2u/learn-javascript/commit/7293fdd7403b67bd3cb1fe965312cb03f3227c71) commit.
